### ISSUE TITLE
Проблема c MySQL 5/5

### ISSUE THREAD

**Issue by iHuntersteam** [iHuntersteam/iHunters#3]
Проблема с SQL скриптом ihunters_schema.sql

**Таблица Sites**

```
name NVARCHAR( 256)

Ошибка #1071 - Specified key was too long; max key length is 767 bytes
```

**Таблица Pages**

```
found_date_time DATETIME DEFAULT CURRENT_TIMESTAMP,
last_scan_date DATETIME ON UPDATE CURRENT_TIMESTAMP ,
url_hashCHAR( 32)UNIQUE ,

Ошибка #1067 - Invalid default value for 'found_date_time'
```

```
Ошибка #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 
'CURRENT_TIMESTAMP, last_scan_date DATETIME ON UPDATE CURRENT_TIMESTAMP, url' at line 5

```

**Comment by pirr** [comment]
https://github.com/iHuntersteam/iHunters/commit/741f96b5f67034fb5f8293dccd3a9c0068346104 - исправлены DATETIME на TIMESTAMP, теперь на 5.5 и ниже не должно быть этой ошибки
по NVARCHAR(256) - Отпишитесь еще у кого та же проблема и какую версию MySQL используете

**Comment by pirr** [comment]
**Проблема в версии MySQL 5.5 и ниже. Было решено использовать MySQL не ниже 5.6.**
